### ISSUE TITLE
Can you send me the SRD test dataset?

### ISSUE THREAD

**Issue by XiaMoooo** [zysxmu/HQSS#1]
I found out that the SRD official link is not working. I tried to contact the author but failed. So, please, do you still have the relevant dataset? If you still have it, can you send me an email? My email : fj031717xiamo@163.com
Thank you very much！！

**Comment by zysxmu** [comment]
Sorry for the late reply. I will check if the SRD dataset still exists on our server.

**Comment by zysxmu** [comment]
According to the license, it should ask the original author of the SRD dataset to get the link.
